export const packages = [
  {
    id: 'coxs-bazar-3n4d',
    slug: 'coxs-bazar-3n4d',
    title: "Cox's Bazar Escape",
    subtitle: '3 Nights / 4 Days',
    category: 'domestic',
    destination: "Cox's Bazar, Bangladesh",
    price: 8500,
    originalPrice: 10500,
    currency: 'BDT',
    image: '/images/coxs-bazar.png',
    rating: 4.9,
    reviews: 312,
    duration: '4 days',
    groupSize: '2–15 persons',
    highlights: ['Sunset at Inani Beach', 'Sea-fresh seafood dinner', 'Himchari National Park', 'Ramu Buddhist temples'],
    badge: 'Best Seller',
    badgeColor: 'gold',
  },
  {
    id: 'sundarbans-2n3d',
    slug: 'sundarbans-2n3d',
    title: 'Sundarbans Expedition',
    subtitle: '2 Nights / 3 Days',
    category: 'domestic',
    destination: 'Sundarbans, Bangladesh',
    price: 6800,
    originalPrice: 8500,
    currency: 'BDT',
    image: '/images/sundarbans.png',
    rating: 4.8,
    reviews: 178,
    duration: '3 days',
    groupSize: '4–20 persons',
    highlights: ['Royal Bengal Tiger zone', 'Mangrove boat cruise', 'Bird watching tour', 'Forest eco-lodge stay'],
    badge: 'Eco Tour',
    badgeColor: 'green',
  },
  {
    id: 'bandarban-3n4d',
    slug: 'bandarban-3n4d',
    title: 'Bandarban Hill Trek',
    subtitle: '3 Nights / 4 Days',
    category: 'domestic',
    destination: 'Bandarban, Bangladesh',
    price: 7200,
    originalPrice: 9000,
    currency: 'BDT',
    image: '/images/bandarban.png',
    rating: 4.7,
    reviews: 145,
    duration: '4 days',
    groupSize: '2–12 persons',
    highlights: ['Boga Lake trek', 'Nilgiri peak sunrise', 'Chingri Waterfalls', 'Indigenous village visit'],
    badge: 'Adventure',
    badgeColor: 'brand',
  },
  {
    id: 'maldives-5n6d',
    slug: 'maldives-5n6d',
    title: 'Maldives Paradise',
    subtitle: '5 Nights / 6 Days',
    category: 'international',
    destination: 'Maldives',
    price: 85000,
    originalPrice: 105000,
    currency: 'BDT',
    image: '/images/maldives.png',
    rating: 5.0,
    reviews: 264,
    duration: '6 days',
    groupSize: '2–8 persons',
    highlights: ['Water villa stay', 'Snorkeling & diving', 'Sunset dolphin cruise', 'Spa & wellness retreat'],
    badge: 'Luxury',
    badgeColor: 'gold',
  },
  {
    id: 'bali-6n7d',
    slug: 'bali-6n7d',
    title: 'Bali Bliss',
    subtitle: '6 Nights / 7 Days',
    category: 'international',
    destination: 'Bali, Indonesia',
    price: 72000,
    originalPrice: 90000,
    currency: 'BDT',
    image: '/images/bali.png',
    rating: 4.9,
    reviews: 198,
    duration: '7 days',
    groupSize: '2–10 persons',
    highlights: ['Ubud rice terraces', 'Uluwatu cliff temple', 'Traditional Kecak dance', 'Seminyak beach clubs'],
    badge: 'Popular',
    badgeColor: 'brand',
  },
  {
    id: 'turkey-7n8d',
    slug: 'turkey-7n8d',
    title: 'Türkiye Discovery',
    subtitle: '7 Nights / 8 Days',
    category: 'international',
    destination: 'Istanbul & Cappadocia, Turkey',
    price: 120000,
    originalPrice: 148000,
    currency: 'BDT',
    image: '/images/turkey.png',
    rating: 4.9,
    reviews: 231,
    duration: '8 days',
    groupSize: '2–16 persons',
    highlights: ['Hagia Sophia & Blue Mosque', 'Cappadocia hot air balloon', 'Grand Bazaar shopping', 'Bosphorus dinner cruise'],
    badge: 'Hot Deal',
    badgeColor: 'red',
  },
  {
    id: 'umrah-standard',
    slug: 'umrah-standard',
    title: 'Umrah Standard Package',
    subtitle: '14 Nights / 15 Days',
    category: 'umrah',
    destination: 'Makkah & Madinah, Saudi Arabia',
    price: 145000,
    originalPrice: 168000,
    currency: 'BDT',
    image: '/images/makkah.png',
    rating: 5.0,
    reviews: 445,
    duration: '15 days',
    groupSize: '10–50 persons',
    highlights: ['Return Dhaka–Jeddah flights', '4-star hotel in Makkah', '4-star hotel in Madinah', 'Guided Ziyarat tours'],
    badge: 'Most Trusted',
    badgeColor: 'gold',
  },
]

export const destinations = [
  {
    id: 'coxs-bazar',
    name: "Cox's Bazar",
    country: 'Bangladesh',
    image: '/images/coxs-bazar.png',
    packages: 12,
    tag: 'Domestic',
  },
  {
    id: 'maldives',
    name: 'Maldives',
    country: 'Indian Ocean',
    image: '/images/maldives.png',
    packages: 8,
    tag: 'International',
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    image: '/images/bali.png',
    packages: 6,
    tag: 'International',
  },
  {
    id: 'turkey',
    name: 'Türkiye',
    country: 'Turkey',
    image: '/images/turkey.png',
    packages: 7,
    tag: 'International',
  },
  {
    id: 'sundarbans',
    name: 'Sundarbans',
    country: 'Bangladesh',
    image: '/images/sundarbans.png',
    packages: 5,
    tag: 'Eco Tour',
  },
  {
    id: 'makkah',
    name: 'Makkah & Madinah',
    country: 'Saudi Arabia',
    image: '/images/makkah.png',
    packages: 9,
    tag: 'Umrah & Hajj',
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Rafiqul Islam',
    location: 'Dhaka',
    package: 'Maldives Paradise Package',
    rating: 5,
    text: "Horizon Travels made our honeymoon absolutely magical. Every detail was perfect — from the water villa to the sunset cruise. Their team was available on WhatsApp 24/7 throughout our trip. Highly recommend!",
    avatar: 'RI',
  },
  {
    id: 2,
    name: 'Nasrin Akter',
    location: 'Chittagong',
    package: 'Umrah Standard Package',
    rating: 5,
    text: "Alhamdulillah, performing Umrah with Horizon Travels was a deeply spiritual and seamless experience. The hotels were excellent, the guides were knowledgeable, and our group felt safe throughout.",
    avatar: 'NA',
  },
  {
    id: 3,
    name: 'Tanvir Ahmed',
    location: 'Sylhet',
    package: "Cox's Bazar Escape",
    rating: 5,
    text: "We went as a family of 7 and had zero issues. Pickup was on time, hotel was clean and well-located, and the guided itinerary was excellent. Booking via bKash was super convenient too!",
    avatar: 'TA',
  },
  {
    id: 4,
    name: 'Shahana Begum',
    location: 'Rajshahi',
    package: 'Türkiye Discovery',
    rating: 5,
    text: "The Istanbul and Cappadocia trip exceeded all our expectations. The hot air balloon was breathtaking. Horizon Travels handled everything including the visa — stress-free from start to finish.",
    avatar: 'SB',
  },
  {
    id: 5,
    name: 'Mahmud Hassan',
    location: 'Khulna',
    package: 'Sundarbans Expedition',
    rating: 5,
    text: "A truly unique eco-adventure. We spotted a Royal Bengal Tiger! The jungle lodge was cozy and the boat cruise through the mangroves was unlike anything I've experienced before.",
    avatar: 'MH',
  },
]

export const services = [
  {
    id: 'domestic',
    icon: 'MapPin',
    title: 'Domestic Tours',
    description: "Expert-crafted packages to Bangladesh's most beautiful destinations — Cox's Bazar, Sundarbans, Bandarban, Sylhet, and more.",
  },
  {
    id: 'international',
    icon: 'Globe',
    title: 'International Tours',
    description: 'Curated international packages to the Maldives, Bali, Turkey, Thailand, Singapore, Malaysia, Europe, and beyond.',
  },
  {
    id: 'umrah',
    icon: 'Star',
    title: 'Umrah & Hajj',
    description: 'Government-approved, spiritually enriching Umrah and Hajj packages with premium hotels and expert guides.',
  },
  {
    id: 'visa',
    icon: 'FileText',
    title: 'Visa Assistance',
    description: 'End-to-end visa processing support for tourist, business, student, and medical visas across 50+ countries.',
  },
  {
    id: 'airticket',
    icon: 'Plane',
    title: 'Air Tickets',
    description: 'Best-price airfare on all major international and domestic airlines with flexible booking and cancellation policies.',
  },
  {
    id: 'hotel',
    icon: 'Building2',
    title: 'Hotel Booking',
    description: 'Handpicked hotels from budget-friendly to ultra-luxury across all destinations, with verified reviews and best-rate guarantees.',
  },
]

export const stats = [
  { value: '15,000+', label: 'Happy Travelers' },
  { value: '12+', label: 'Years of Excellence' },
  { value: '80+', label: 'Destinations Covered' },
  { value: '99%', label: 'Client Satisfaction' },
]

export const faqs = [
  {
    question: 'How do I book a tour package?',
    answer: 'You can book directly through our website by clicking "Book Now" on any package, or contact us via WhatsApp, phone, or visit our office. We accept bKash, Nagad, card payments, and bank transfers.',
  },
  {
    question: 'What payment methods do you accept?',
    answer: 'We accept bKash, Nagad, Rocket, all major debit/credit cards, and direct bank transfers. A 30% advance is required to confirm the booking, with the balance due 7 days before departure.',
  },
  {
    question: 'Can I customize a tour package?',
    answer: 'Absolutely! All our packages are fully customizable. Tell us your travel dates, group size, budget, and preferences, and our travel experts will craft a personalized itinerary just for you.',
  },
  {
    question: 'Do you provide visa assistance?',
    answer: 'Yes, we provide comprehensive visa assistance for tourist, business, student, and medical visas for 50+ countries. Our success rate is above 98%. We guide you through every step of the process.',
  },
  {
    question: 'What is your cancellation and refund policy?',
    answer: 'Cancellations made 30+ days before departure receive a full refund (minus processing fees). 15–29 days prior: 50% refund. Less than 15 days: no refund. We strongly recommend travel insurance.',
  },
  {
    question: 'Are your Umrah packages government approved?',
    answer: 'Yes. Horizon Travels is a licensed and government-approved Hajj & Umrah agency registered with the Ministry of Religious Affairs, Bangladesh. All our Umrah packages comply with Saudi regulations.',
  },
]
